# Generated by Django 3.0 on 2020-07-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200713_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], null=True),
        ),
    ]
